graph TD
    dz2 --> colorama
    dz2 --> filelock
    dz2 --> fsspec
    dz2 --> iniconfig
    dz2 --> Jinja2
    dz2 --> MarkupSafe
    dz2 --> mathplot
    dz2 --> mpmath
    dz2 --> networkx
    dz2 --> numpy
    dz2 --> packaging
    dz2 --> pandas
    dz2 --> pluggy
    dz2 --> pytest
    dz2 --> python-dateutil
    dz2 --> pytz
    dz2 --> setuptools
    dz2 --> six
    dz2 --> sympy
    dz2 --> toml
    dz2 --> torch
    dz2 --> typing_extensions
    dz2 --> tzdata